name: docker
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with: {driver-opts: network=host}
    - uses: actions/setup-python@v2
      with: {python-version: 3.7}
    - run: pip install -q --no-input poetry
    - run: |
        poetry remove -D grpcio-tools --dry-run
        poetry export -E rocksdb -o requirements.txt
        ls -la
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: localhost:5000/foo/bar:latest
        platforms: linux/amd64,linux/arm64
    - run: docker buildx imagetools inspect localhost:5000/foo/bar:latest
